export interface BountyPool {
  id: string;
  title: string;
  startup: string;
  logo: string;
  category: "TikTok" | "Reels" | "Shorts" | "X / Twitter" | "Multi-Platform";
  cpmRate: number; // $ per 1,000 verified views (e.g., 2.00)
  totalBudget: number; // Total pool budget (e.g., 10000)
  remainingBudget: number; // Money remaining in pool
  totalViewsGenerated: number; // Total views generated by clippers
  minViewsThreshold: number; // e.g. 1000 views minimum
  maxCapPerVideo: number; // e.g. $150 per video cap
  status: "ACTIVE POOL" | "HOT BOUNTY" | "FAST FILLING";
  hashtags: string[];
  rawAssetUrl: string; // Link to Google Drive / Notion raw footage
  description: string;
}

export const INITIAL_BOUNTIES: BountyPool[] = [
  {
    id: "novaai-tiktok-clips",
    title: "NovaAI AI Coding Workflows - AZYRA Clips Bounty",
    startup: "NovaAI",
    logo: "🚀",
    category: "TikTok",
    cpmRate: 2.00, // $2.00 per 1,000 views
    totalBudget: 15000,
    remainingBudget: 4250,
    totalViewsGenerated: 5375000,
    minViewsThreshold: 1000,
    maxCapPerVideo: 250,
    status: "HOT BOUNTY",
    hashtags: ["#NovaAI", "#CodingHack", "#DevLife", "#AItools"],
    rawAssetUrl: "https://drive.google.com/drive/folders/novaai-raw-clips",
    description: "Edit high-energy 15-60s videos using raw founder podcast footage & screen demos showing NovaAI generating full-stack apps in 30 seconds.",
  },
  {
    id: "flowx-shorts-bounty",
    title: "FlowX DevTools Latency Failures & Fixes",
    startup: "FlowX",
    logo: "⚡",
    category: "Shorts",
    cpmRate: 1.75, // $1.75 per 1,000 views
    totalBudget: 10000,
    remainingBudget: 3100,
    totalViewsGenerated: 3942000,
    minViewsThreshold: 1000,
    maxCapPerVideo: 200,
    status: "ACTIVE POOL",
    hashtags: ["#FlowX", "#WebDev", "#Nextjs", "#CodingFail"],
    rawAssetUrl: "https://drive.google.com/drive/folders/flowx-assets",
    description: "Take server crash meme clips or developer commentary footage and overlay FlowX telemetry graphs to show instant bottleneck detection.",
  },
  {
    id: "pixelpay-reels-bounty",
    title: "PixelPay Nomad Micropayments & Crypto Escrow",
    startup: "PixelPay",
    logo: "💳",
    category: "Reels",
    cpmRate: 1.50, // $1.50 per 1,000 views
    totalBudget: 8000,
    remainingBudget: 2400,
    totalViewsGenerated: 3733000,
    minViewsThreshold: 1000,
    maxCapPerVideo: 150,
    status: "FAST FILLING",
    hashtags: ["#PixelPay", "#DigitalNomad", "#RemoteWork", "#Fintech"],
    rawAssetUrl: "https://drive.google.com/drive/folders/pixelpay-nomad-clips",
    description: "Clip digital nomad travel videos & freelance invoice struggles showing how PixelPay pays out internationally with zero FX margin.",
  },
  {
    id: "hyperscale-x-clipping",
    title: "HyperScale Edge Infrastructure vs AWS Benchmark Clips",
    startup: "HyperScale",
    logo: "🌐",
    category: "X / Twitter",
    cpmRate: 2.50, // $2.50 per 1,000 views
    totalBudget: 20000,
    remainingBudget: 9800,
    totalViewsGenerated: 4080000,
    minViewsThreshold: 2000,
    maxCapPerVideo: 300,
    status: "ACTIVE POOL",
    hashtags: ["#HyperScale", "#CloudArchitecture", "#AWS", "#SystemDesign"],
    rawAssetUrl: "https://drive.google.com/drive/folders/hyperscale-cloud-vods",
    description: "Clip high-density tech talks & speed benchmarks comparing edge deployment vs traditional AWS server delays for software architects.",
  },
];
